root = "."
tmp_dir = "tmp"

[build]
    cmd = "go build -o ./tmp/tsunuga ./cmd/tsunuga"
    bin = "./tmp/tsunuga"
    include_ext = ["go"]
    exclude_ext = ["tmp", "vendor"]

[log]
    time = true

[misc]
    clean_on_exit = true